# Generated by Django 4.2.1 on 2023-06-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='unit',
            field=models.CharField(choices=[('second', 'second'), ('minute', 'minute'), ('hour', 'hour'), ('day', 'day'), ('week', 'week'), ('month', 'month'), ('year', 'year')], default='second', max_length=10),
        ),
    ]
