# Generated by Django 4.2.1 on 2023-06-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_stock_starting_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='volatility',
            field=models.FloatField(default=0.15),
        ),
    ]
