# Generated by Django 4.2.1 on 2023-06-18 20:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_stock_volatility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authenty', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishliststock',
            unique_together={('user', 'stock')},
        ),
    ]
